# Site settings
title: Alex Firth Portfolio
description: Game dev portfolio site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cyverneon.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alex Firth
user_description: Blah blah blah placeholder placeholder
user_title: Gameplay programmer and technical artist
email: cyverneon@gmail.com
twitter_username: cyverneon
github_username:  cyverneon

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
