url: "https://cyverneon.dev" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Alex Firth" # the name of your site, e.g. ACME Corp.

name: Alex Firth
user_title: gameplay programmer and technical artist